# Generated by Django 2.1.3 on 2019-01-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20181217_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiezi',
            name='category',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
