# Generated by Django 2.1.3 on 2019-01-05 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_tiezi_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_dongtai',
            name='nickname',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='forum.Userinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment_tiezi',
            name='nickname',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='forum.Userinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dongtai',
            name='nickname',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='forum.Userinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiezi',
            name='nickname',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='forum.Userinfo'),
            preserve_default=False,
        ),
    ]
