# Generated by Django 2.1.3 on 2019-01-05 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20190105_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_dongtai',
            old_name='nickname',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment_tiezi',
            old_name='nickname',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='dongtai',
            old_name='nickname',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='tiezi',
            old_name='nickname',
            new_name='user',
        ),
    ]
