# Generated by Django 2.1.3 on 2019-01-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20190105_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
